# Generated by Django 4.1.1 on 2022-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.BigIntegerField(verbose_name='id пользователь')),
                ('name', models.TextField(verbose_name='Имя/Ник пользователя')),
                ('email', models.TextField(verbose_name='Почта пользователя')),
                ('programming_lang', models.TextField(verbose_name='Знает языки')),
                ('mast', models.TextField(verbose_name='Сфера разработки')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Инфо рмация о пользователях',
            },
        ),
    ]
