# Generated by Django 4.1.1 on 2022-11-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(verbose_name='Айди вопроса')),
                ('question_text', models.TextField(verbose_name='текст вопроса')),
                ('opt1', models.TextField(verbose_name='ответ1')),
                ('opt2', models.TextField(verbose_name='ответ2')),
                ('opt3', models.TextField(verbose_name='ответ3')),
                ('opt4', models.TextField(verbose_name='ответ4')),
                ('questioner_name', models.TextField(verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
